### ISSUE TITLE
Merge with Henson's website?

### ISSUE THREAD

**Issue by gllmflndn** [jbwexler/ds000117_R1.0.0_empty#1]
Hi Joe,

Thanks for this. There is already an attempt at a BIDS conversion of the MRI part of this dataset here:
  ftp://ftp.mrc-cbu.cam.ac.uk/personal/rik.henson/wakemandg_hensonrn/BIDS/
Do you think it would be possible to merge the two efforts and add the MEG part?

Also, according to the BIDS specs, behavioral files `_events.tsv` should not have a `sub-*_` prefix.

Many thanks.

**Comment by jbwexler** [comment]
Good idea! Let me spend some time looking at this and I'll try to figure out whether to try to merge them.

Also, as far as I know, the issue you mentioned about events files was a typo in the version 1.0.0 of the BIDS spec. In the release candidate for 1.0.1, this has been fixed: http://bids.neuroimaging.io/bids_spec1.0.1-rc1.pdf
