### ISSUE TITLE
TSV behavioral files

### ISSUE THREAD

**Issue by gllmflndn** [jbwexler/ds000117_R1.0.0_empty#5]
TSV behavioral files are badly formed with a spurious `\r` at the end of the first column, see e.g.:
https://github.com/jbwexler/ds000117_R1.0.0_empty/blob/master/ds000117_R1.0.0/sub-01/ses-meg/beh/sub-01_ses-meg_task-facerecognition_events.tsv

**Comment by jbwexler** [comment]
nice find. i just fixed this and also converted to seconds
