### ISSUE TITLE
fMRI events.tsv files

### ISSUE THREAD

**Issue by gllmflndn** [jbwexler/ds000117_R1.0.0_empty#6]
The `events.tsv` files for fMRI data don't seem to match the original dataset, see e.g.:
https://github.com/jbwexler/ds000117_R1.0.0_empty/blob/master/ds000117_R1.0.0/sub-01/ses-mri/func/sub-01_ses-mri_task-facerecognition_run-01_events.tsv
vs
ftp://ftp.mrc-cbu.cam.ac.uk/personal/rik.henson/wakemandg_hensonrn/Sub01/BOLD/Trials/run_01_spmdef.txt
(BIDS-formatted version: ftp://ftp.mrc-cbu.cam.ac.uk/personal/rik.henson/wakemandg_hensonrn/BIDS/sub-Sub01/func/sub-Sub01_task-facerecognition_run-01_events.tsv)

**Comment by jbwexler** [comment]
Good find. From a quick glance, it looks they are offset by 4 seconds. Do you know which are correct? From the BIDS doc: "Please note that the onsets recorded in the _event.tsv file should always refer to the beginning of the acquisition of the first volume in the corresponding imaging file - independent of the value of NumberOfVolumesDiscardedByScanner field."
